# Site settings
title: Xu Chen
description: Assistant Professor, the University of Connecticut
email: xchen[AT]uconn.edu
url: "https://xchen-me.github.io"
baseurl: "" # the base hostname & protocol for your site
#favicon
favicon: "/img/Xicon.ico"
me-img: "/img/XuChen.jpg"


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#212121'
  links: '#219ab3'
  
#feed
# feedburner_username: 
#twitter
# twitter_username: xuchen_14
github_username: xchen-me

#linkedin
linkedin_username: "in/xu-chen-61416a1a"

#google analytics
google_analytics_id : UA-51857041-1
#gplus
# gplus_username: 101893920934936418705

#fb_username
# fb_username: 

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
# disqus_short_name: maangalabscom
# disqus_show_comment_count: true
